### PR TITLE
Erlang

### PR DESCRIPTION
**Pull request by WillSewell**
Previous discussion: https://gitlab.com/gasche/gc-latency-experiment/merge_requests/14

### CODE REVIEW

**Comment by WillSewell** [comment]
Hey @filipevarjao, I would like to get this merged, but I don't have Erlang experience, and there's a couple of things I'm not sure about.

* When I run the benchmark I don't get any output, do you know why this is? I'm using Docker to run it (see latest commit)
* It looks like this benchmark isn't measuring the same thing as the other benchmarks: it looks like it is just measuring the time to allocate a single "message". Since the message is discarded on each call to `push_message`, there is only a single "message" object being referenced at a given moment in time. This is  in contrast to the other benchmarks that allocate an array of references to messages, and at each iteration an existing reference is replaces by a reference to a new message. Am I misunderstanding something about your benchmark?

**Comment by filipevarjao** [comment]
cool, I'll take a look and get back to you

**Comment by filipevarjao** [comment]
hey, @WillSewell, I tried to push my changes, but I don't have permission. Could you give me the rights? or do you prefer that I fork the project to open a new PR?

**Comment by WillSewell** [comment]
Hey, sorry for the delay @filipevarjao. That's great you have made some changes :)

Unfortunately it looks like the only why I can give you permission is to give your write access to the whole repo. It's probably best if you create a fork and create a new branch of this branch, and submit that as a new PR with this branch as the base branch.

**Pull request merged**
