### PR TITLE
Haskell version should print GHC runtime statistics with +RTS -s

### PR DESCRIPTION
**Pull request by jameshfisher**

### CODE REVIEW

**Comment by WillSewell** [comment]
The runtime statistics might not be useful to everyone; would be be ok to turn them on if desired with `docker run gc-haskell +RTS -s`?

**Comment by jameshfisher** [comment]
@WillSewell was your goal to get every program printing a single number in the same format? (i.e. this RTS output is extra noise)

**Comment by WillSewell** [comment]
That was the goal. It makes it easier for someone who is not familiar with the tooling of a particular languages to interpret and compare results. Plus it makes the output machine-readable.

**Comment by WillSewell** [comment]
I wouldn't be opposed to a README in each language-specific directory with some more detail and possible options to get runtime system output.

**Pull request closed without merging**
